[default]
before = "cd src/rs; cargo build --lib --release"
out = "uss"
oarg = [
    "-Ofast",
    "-std=c++17",
    "-fopenmp",
    "`pkg-config guile-3.0 --cflags --libs`",
    "-Lsrc/rs/target/release"
]
l = [
  "rs"
]
com = "g++"
relink = [
"src/rs/.*\\.rs"
]

[_default]
inherits = "default"
 
[_debug]
inherits = "default"
oarg = [
    "-g",
]

[gdb]
type = "command"
target = "_debug"
command = "gdb $EXECUTABLE -ex run -ex continue"

[run]
type = "command"
target = "_debug"
command = "$EXECUTABLE"