[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-raknet = "*"
tokio = "*"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"